version: '3.8'

services:
  db:
    image: postgres:alpine3.19
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d course_informer" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    labels:
      - "service=db"
    networks:
      - db-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KEY_ALIAS: ${KEY_ALIAS}
        PRIVATE_KEY_PASSWORD: ${PRIVATE_KEY_PASSWORD}
        KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
        JDBC_H2_URL: ${JDBC_H2_URL}
        JDBC_H2_DRIVER: ${JDBC_H2_DRIVER}
        JDBC_POSTGRES_DRIVER: ${JDBC_POSTGRES_DRIVER}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        BASE_URL: ${BASE_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        KEYSTORE_URL: ${KEYSTORE_URL}
    depends_on:
      db:
        condition: service_healthy
    environment:
      KEY_ALIAS: ${KEY_ALIAS}
      PRIVATE_KEY_PASSWORD: ${PRIVATE_KEY_PASSWORD}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      JDBC_H2_URL: ${JDBC_H2_URL}
      JDBC_H2_DRIVER: ${JDBC_H2_DRIVER}
      JDBC_POSTGRES_DRIVER: ${JDBC_POSTGRES_DRIVER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JDBC_DRIVER: ${JDBC_POSTGRES_DRIVER}
      JDBC_URL: ${JDBC_DATABASE_URL}
      BASE_URL: ${BASE_URL}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      KEYSTORE_URL: ${KEYSTORE_URL}
    networks:
      - app-network
      - db-network
    ports:
      - "8080:80"
      - "8443:443"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-k", "https://localhost:8443/health" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: on-failure
    labels:
      - "service=app"

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
